version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
